### ISSUE TITLE
TrakHound Server Crashes editing New item

### ISSUE THREAD

**Issue by iambkramer** [TrakHound/TrakHound#26]
whenever I try to edit a new item on Trakhound server  as soon as I hit save the software crashes.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	TrakHound-Server-DeviceManager
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	57396c62
  Problem Signature 04:	TH_DeviceManager
  Problem Signature 05:	2.0.0.0
  Problem Signature 06:	57396c58
  Problem Signature 07:	50
  Problem Signature 08:	59
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	1318
  Additional Information 4:	13181ae637ac2592fac0ca2dd662cdcc

**Comment by PatrickRitchie** [comment]
Thanks @iambkramer for taking the time to create an Issue! The Device Manager for TrakHound Server is a new feature as we are still trying to figure out exactly what to include with the 'Server Only' install. I spent some time redesigning the window and fixed the issue you were having when trying to edit a device and it will be available in v1.12.0.

![server-device-manager-redesign](https://cloud.githubusercontent.com/assets/13772118/15441885/8912dd66-1eab-11e6-8c51-d81bc0806952.png)
